name: encryption_app
description: Encrypt text with password
publish_to: 'none'
version: 6.11.0+29

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  bot_toast: ^4.1.3
  clipboard: ^2.0.2
  package_info_plus: ^9.0.0
  smooth_page_indicator: ^1.2.1
  sizer: ^3.1.3
  easy_localization: ^3.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  selectable_autolink_text: ^2.6.0
  in_app_review: ^2.0.11
  showcaseview: ^5.0.1
  local_auth: ^3.0.0
  flutter_inset_box_shadow:
    path: packages/flutter_inset_box_shadow-1.0.8
  receive_sharing_intent: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.10.1
  mockito: ^5.5.1
  flutter_lints: ^6.0.0

dependency_overrides:
  win32: ^5.15.0
  lints: ^5.1.1
  analyzer: ^8.0.0
  source_gen: ">=3.0.0 <5.0.0"
  build: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - fonts/baloo/

  fonts:
    - family: Baloo
      fonts:
        - asset: fonts/baloo/BalooBhaijaan2-Regular.ttf
          weight: 500


    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
